//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luna.Resources.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class I18N {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18N() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Luna.Resources.Langs.I18N", typeof(I18N).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Delete all scripts? 的本地化字符串。
        /// </summary>
        internal static string ConfirmDeleteAllScripts {
            get {
                return ResourceManager.GetString("ConfirmDeleteAllScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure want to remove this script? 的本地化字符串。
        /// </summary>
        internal static string ConfirmRemoveScript {
            get {
                return ResourceManager.GetString("ConfirmRemoveScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lua Scripts manager.（require 64bit system) 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discard unsaved changes? 的本地化字符串。
        /// </summary>
        internal static string DiscardUnsavedChanges {
            get {
                return ResourceManager.GetString("DiscardUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done. 的本地化字符串。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty 的本地化字符串。
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export scripts fail! 的本地化字符串。
        /// </summary>
        internal static string ExportScriptsFail {
            get {
                return ResourceManager.GetString("ExportScriptsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail! 的本地化字符串。
        /// </summary>
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import scripts fail! 的本地化字符串。
        /// </summary>
        internal static string ImportScriptsFail {
            get {
                return ResourceManager.GetString("ImportScriptsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import scripts success! 的本地化字符串。
        /// </summary>
        internal static string ImportScriptsSuccess {
            get {
                return ResourceManager.GetString("ImportScriptsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E 的本地化字符串。
        /// </summary>
        internal static string LuaCtrlOptionNone {
            get {
                return ResourceManager.GetString("LuaCtrlOptionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Luna v{0} - script editor 的本地化字符串。
        /// </summary>
        internal static string LunaScrEditor {
            get {
                return ResourceManager.GetString("LunaScrEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Luna v{0} - script manager 的本地化字符串。
        /// </summary>
        internal static string LunaScrMgr {
            get {
                return ResourceManager.GetString("LunaScrMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open script editor 的本地化字符串。
        /// </summary>
        internal static string OpenScriptEditor {
            get {
                return ResourceManager.GetString("OpenScriptEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open script manager 的本地化字符串。
        /// </summary>
        internal static string OpenScriptManger {
            get {
                return ResourceManager.GetString("OpenScriptManger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace script: 的本地化字符串。
        /// </summary>
        internal static string ReplaceScript {
            get {
                return ResourceManager.GetString("ReplaceScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script name not set! 的本地化字符串。
        /// </summary>
        internal static string ScriptNameNotSet {
            get {
                return ResourceManager.GetString("ScriptNameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script not found! 的本地化字符串。
        /// </summary>
        internal static string ScriptNotFound {
            get {
                return ResourceManager.GetString("ScriptNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 send stop signal to  的本地化字符串。
        /// </summary>
        internal static string SendStopSignalTo {
            get {
                return ResourceManager.GetString("SendStopSignalTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 start 的本地化字符串。
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 stopped 的本地化字符串。
        /// </summary>
        internal static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 terminate 的本地化字符串。
        /// </summary>
        internal static string Terminate {
            get {
                return ResourceManager.GetString("Terminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write file fail! 的本地化字符串。
        /// </summary>
        internal static string WriteFileFail {
            get {
                return ResourceManager.GetString("WriteFileFail", resourceCulture);
            }
        }
    }
}
