//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Composer.Resources.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class I18N {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18N() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Composer.Resources.Langs.I18N", typeof(I18N).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Delete package: 的本地化字符串。
        /// </summary>
        internal static string ConfirmDelPkg {
            get {
                return ResourceManager.GetString("ConfirmDelPkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compose servers outbound config. 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not open multiple server selector windows. 的本地化字符串。
        /// </summary>
        internal static string ErrCanNotOpenMulFormServSelector {
            get {
                return ResourceManager.GetString("ErrCanNotOpenMulFormServSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: package name is empty! 的本地化字符串。
        /// </summary>
        internal static string ErrPkgNameIsEmpty {
            get {
                return ResourceManager.GetString("ErrPkgNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: server with same config already exists! 的本地化字符串。
        /// </summary>
        internal static string ErrSameConfigExists {
            get {
                return ResourceManager.GetString("ErrSameConfigExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: tag is empty! 的本地化字符串。
        /// </summary>
        internal static string ErrTagIsEmpty {
            get {
                return ResourceManager.GetString("ErrTagIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Has filter. 的本地化字符串。
        /// </summary>
        internal static string HasFilter {
            get {
                return ResourceManager.GetString("HasFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom servers 的本地化字符串。
        /// </summary>
        internal static string Nodes {
            get {
                return ResourceManager.GetString("Nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package not exist! 的本地化字符串。
        /// </summary>
        internal static string PackageNotExist {
            get {
                return ResourceManager.GetString("PackageNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack servers failed. 的本地化字符串。
        /// </summary>
        internal static string PackServFailed {
            get {
                return ResourceManager.GetString("PackServFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack servers success. 的本地化字符串。
        /// </summary>
        internal static string PackServSuccess {
            get {
                return ResourceManager.GetString("PackServSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 total({2}) = filter({0}) + others({1}) 的本地化字符串。
        /// </summary>
        internal static string TotalLabelText {
            get {
                return ResourceManager.GetString("TotalLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknow template name: 的本地化字符串。
        /// </summary>
        internal static string UnkownTemplateName {
            get {
                return ResourceManager.GetString("UnkownTemplateName", resourceCulture);
            }
        }
    }
}
