//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VgcApis.Resources.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class I18N {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18N() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VgcApis.Resources.Langs.I18N", typeof(I18N).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear log? 的本地化字符串。
        /// </summary>
        internal static string ConfirmClearLog {
            get {
                return ResourceManager.GetString("ConfirmClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load file [{0}]? 的本地化字符串。
        /// </summary>
        internal static string ConfirmLoadFileContent {
            get {
                return ResourceManager.GetString("ConfirmLoadFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut 的本地化字符串。
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done. 的本地化字符串。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File [{0}] is empty. 的本地化字符串。
        /// </summary>
        internal static string FileIsEmpty {
            get {
                return ResourceManager.GetString("FileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max keyword length is 100 character. 的本地化字符串。
        /// </summary>
        internal static string KeywordIsTooLong {
            get {
                return ResourceManager.GetString("KeywordIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No match result! 的本地化字符串。
        /// </summary>
        internal static string NoMatchResult {
            get {
                return ResourceManager.GetString("NoMatchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please do search first. 的本地化字符串。
        /// </summary>
        internal static string PlsDoSearchFirst {
            get {
                return ResourceManager.GetString("PlsDoSearchFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo 的本地化字符串。
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replaced {0} times. 的本地化字符串。
        /// </summary>
        internal static string ReplacedCount {
            get {
                return ResourceManager.GetString("ReplacedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as 的本地化字符串。
        /// </summary>
        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select all 的本地化字符串。
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write to file fail! 的本地化字符串。
        /// </summary>
        internal static string WriteFileFail {
            get {
                return ResourceManager.GetString("WriteFileFail", resourceCulture);
            }
        }
    }
}
