//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace V2RayGCon.Resource.Resx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StrConst {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StrConst() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V2RayGCon.Resource.Resx.StrConst", typeof(StrConst).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;reverseDefault&quot;: {
        ///    &quot;bridges&quot;: [
        ///      {
        ///        &quot;tag&quot;: &quot;bridge&quot;,
        ///        &quot;domain&quot;: &quot;test.v2ray.com&quot;
        ///      }
        ///    ],
        ///    &quot;portals&quot;: [
        ///      {
        ///        &quot;tag&quot;: &quot;portal&quot;,
        ///        &quot;domain&quot;: &quot;test.v2ray.com&quot;
        ///      }
        ///    ]
        ///  },
        ///  &quot;inTpl&quot;: {
        ///    &quot;port&quot;: 1080,
        ///    &quot;listen&quot;: &quot;127.0.0.1&quot;,
        ///    &quot;protocol&quot;: &quot;协议名称&quot;,
        ///    &quot;settings&quot;: {},
        ///    &quot;streamSettings&quot;: {},
        ///    &quot;tag&quot;: &quot;标识&quot;,
        ///    &quot;sniffing&quot;: {
        ///      &quot;enabled&quot;: false,
        ///      &quot;destOverride&quot;: [
        ///        &quot;http&quot;,
        ///        &quot;tls&quot;
        ///      ]
        ///    }
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string config_example {
            get {
                return ResourceManager.GetString("config_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;log&quot;: {
        ///    &quot;loglevel&quot;: &quot;warning&quot;
        ///  },
        ///  &quot;inbounds&quot;: [
        ///    {
        ///      &quot;port&quot;: 1080,
        ///      &quot;listen&quot;: &quot;127.0.0.1&quot;,
        ///      &quot;protocol&quot;: &quot;socks&quot;,
        ///      &quot;settings&quot;: {
        ///        &quot;auth&quot;: &quot;noauth&quot;,
        ///        &quot;udp&quot;: false,
        ///        &quot;ip&quot;: &quot;127.0.0.1&quot;
        ///      }
        ///    }
        ///  ],
        ///  &quot;outbounds&quot;: [
        ///    {
        ///      &quot;protocol&quot;: &quot;freedom&quot;,
        ///      &quot;settings&quot;: {},
        ///      &quot;tag&quot;: &quot;direct&quot;
        ///    }
        ///  ],
        ///  &quot;policy&quot;: {
        ///    &quot;levels&quot;: {
        ///      &quot;0&quot;: {
        ///        &quot;uplinkOnly&quot;: 0
        ///      }
        ///    }
        ///  }
        ///} 的本地化字符串。
        /// </summary>
        internal static string config_min {
            get {
                return ResourceManager.GetString("config_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;pkgV4Tpl&quot;: {
        ///    &quot;log&quot;: {
        ///      &quot;loglevel&quot;: &quot;warning&quot;
        ///    },
        ///    &quot;v2raygcon&quot;: {
        ///      &quot;alias&quot;: &quot;PackageV4&quot;,
        ///      &quot;description&quot;: &quot;&quot;
        ///    },
        ///    &quot;routing&quot;: {
        ///      &quot;balancers&quot;: [
        ///        {
        ///          &quot;tag&quot;: &quot;balancer&quot;,
        ///          &quot;selector&quot;: [
        ///            &quot;agentout&quot;
        ///          ]
        ///        }
        ///      ],
        ///      &quot;rules&quot;: [
        ///        {
        ///          &quot;type&quot;: &quot;field&quot;,
        ///          &quot;inboundTag&quot;: [
        ///            &quot;agentin&quot;
        ///          ],
        ///          &quot;balancerTag&quot;: &quot;balancer&quot;
        ///        }
        ///      ]
        ///    },
        ///    &quot;inbo [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string config_pkg {
            get {
                return ResourceManager.GetString("config_pkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;statsApiV4Inb&quot;: {
        ///    &quot;inbounds&quot;: [
        ///      {
        ///        &quot;listen&quot;: &quot;127.0.0.1&quot;,
        ///        &quot;port&quot;: 1090,
        ///        &quot;protocol&quot;: &quot;dokodemo-door&quot;,
        ///        &quot;settings&quot;: {
        ///          &quot;address&quot;: &quot;127.0.0.1&quot;
        ///        },
        ///        &quot;tag&quot;: &quot;StatsApiInb&quot;
        ///      }
        ///    ]
        ///  },
        ///  &quot;statsApiV4Tpl&quot;: {
        ///    &quot;policy&quot;: {
        ///      &quot;levels&quot;: {
        ///        &quot;0&quot;: {
        ///          &quot;statsUserUplink&quot;: true,
        ///          &quot;statsUserDownlink&quot;: true
        ///        }
        ///      },
        ///      &quot;system&quot;: {
        ///        &quot;statsInboundUplink&quot;: true,
        ///        &quot;statsInbound [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string config_tpl {
            get {
                return ResourceManager.GetString("config_tpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0.0.0.0
        ///0.0.0.0/8
        ///1.1
        ///1.1.1.1
        ///10.0.0.0/8
        ///1080
        ///127.0.0.1
        ///192.168.1.1
        ///200
        ///53
        ///8.8.8.8
        ///8080
        ///Accept-Encoding
        ///AsIs
        ///Connection
        ///GET
        ///Host
        ///IPIfNonMatch
        ///IPOnDemand
        ///Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
        ///Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46
        ///OK
        ///Pragma
        ///UseIP
        ///UseIPv4
        ///UseIPv6
        ///V2RAY_BUF_READV
        ///V2RAY_LOCATION_ASSET
        ///V2RAY_ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ConfigJsonKeywords {
            get {
                return ResourceManager.GetString("ConfigJsonKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v3.26 的本地化字符串。
        /// </summary>
        internal static string DefCoreVersion {
            get {
                return ResourceManager.GetString("DefCoreVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/v2ray/v2ray-core/releases/download/{0}/{1} 的本地化字符串。
        /// </summary>
        internal static string DownloadLinkTpl {
            get {
                return ResourceManager.GetString("DownloadLinkTpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vmess://ew0KICAicHMiOiAiZHVtbXkxIiwNCiAgImFkZCI6ICIxLjIuMy40IiwNCiAgInBvcnQiOiAiNDQzIiwNCiAgImlkIjogImI4NzNkNWY0LTMyNjEtNGYxOS04MGE3LWYwZTY3YzkwYzA4MiIsDQogICJhaWQiOiAiMTAwIiwNCiAgIm5ldCI6ICJ3cyIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICIvcmF5IiwNCiAgInRscyI6ICJ0bHMiDQp9 的本地化字符串。
        /// </summary>
        internal static string DummyServ1 {
            get {
                return ResourceManager.GetString("DummyServ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vmess://ew0KICAicHMiOiAiZHVtbXkyIiwNCiAgImFkZCI6ICIyLjMuNC41IiwNCiAgInBvcnQiOiAiMTIzNCIsDQogICJpZCI6ICI1NjIxODM4ZS1hYmM1LTRiNmQtOWQzMS00MmUwOGE3ZWMzMmYiLA0KICAiYWlkIjogIjY0IiwNCiAgIm5ldCI6ICJ0Y3AiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiIiwNCiAgInRscyI6ICIiDQp9 的本地化字符串。
        /// </summary>
        internal static string DummyServ2 {
            get {
                return ResourceManager.GetString("DummyServ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v2ctl.exe 的本地化字符串。
        /// </summary>
        internal static string ExecutableV2ctl {
            get {
                return ResourceManager.GetString("ExecutableV2ctl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v2ray.exe 的本地化字符串。
        /// </summary>
        internal static string ExecutableV2ray {
            get {
                return ResourceManager.GetString("ExecutableV2ray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JS Files|*.js|All File|*.* 的本地化字符串。
        /// </summary>
        internal static string ExtJs {
            get {
                return ResourceManager.GetString("ExtJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PNG Files|*.png|All File|*.* 的本地化字符串。
        /// </summary>
        internal static string ExtPng {
            get {
                return ResourceManager.GetString("ExtPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/v2ray/v2ray-core/releases/latest 的本地化字符串。
        /// </summary>
        internal static string LatestCoreLink {
            get {
                return ResourceManager.GetString("LatestCoreLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.youtube.com/watch?v=BA7fdSkp8ds 的本地化字符串。
        /// </summary>
        internal static string Nobody3uVideoUrl {
            get {
                return ResourceManager.GetString("Nobody3uVideoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /v2ray/v2ray-core/releases/download/(v[\.0-9]+)/v2ray-windows-64.zip 的本地化字符串。
        /// </summary>
        internal static string PatternDownloadLink {
            get {
                return ResourceManager.GetString("PatternDownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /nobody3u/V2RayGCon/releases/tag/([\.0-9]+) 的本地化字符串。
        /// </summary>
        internal static string PatternLatestVGC {
            get {
                return ResourceManager.GetString("PatternLatestVGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v2ray-windows-32.zip 的本地化字符串。
        /// </summary>
        internal static string PkgWin32 {
            get {
                return ResourceManager.GetString("PkgWin32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v2ray-windows-64.zip 的本地化字符串。
        /// </summary>
        internal static string PkgWin64 {
            get {
                return ResourceManager.GetString("PkgWin64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 api --server=&quot;127.0.0.1:{0}&quot; StatsService.GetStats &quot;name: &quot;&quot;&quot;&quot;inbound&gt;&gt;&gt;agentin&gt;&gt;&gt;traffic&gt;&gt;&gt;{1}&quot;&quot;&quot;&quot; reset: true&quot; 的本地化字符串。
        /// </summary>
        internal static string StatsQueryParamTpl {
            get {
                return ResourceManager.GetString("StatsQueryParamTpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/nobody3u/V2RayGCon/releases/tag/{0} 的本地化字符串。
        /// </summary>
        internal static string TplUrlVGCRelease {
            get {
                return ResourceManager.GetString("TplUrlVGCRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/nobody3u/V2RayGCon/releases/latest 的本地化字符串。
        /// </summary>
        internal static string UrlLatestVGC {
            get {
                return ResourceManager.GetString("UrlLatestVGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/v2ray/v2ray-core/releases 的本地化字符串。
        /// </summary>
        internal static string V2rayCoreReleasePageUrl {
            get {
                return ResourceManager.GetString("V2rayCoreReleasePageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/nobody3u/V2RayGCon/wiki/vlink 的本地化字符串。
        /// </summary>
        internal static string VlinkWiki {
            get {
                return ResourceManager.GetString("VlinkWiki", resourceCulture);
            }
        }
    }
}
