//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxySetter.Resources.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StrConst {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StrConst() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProxySetter.Resources.Langs.StrConst", typeof(StrConst).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 030buy.com
        ///0rz.tw
        ///1-apple.com.tw
        ///1000giri.net
        ///100ke.org
        ///10conditionsoflove.com
        ///10musume.com
        ///123rf.com
        ///12bet.com
        ///12vpn.com
        ///12vpn.net
        ///14.102.250.18
        ///14.102.250.19
        ///141hongkong.com
        ///141tube.com
        ///1688.com.au
        ///173ng.com
        ///174.142.105.153
        ///177pic.info
        ///17t17p.com
        ///18board.com
        ///18board.info
        ///18onlygirls.com
        ///18p2p.com
        ///18virginsex.com
        ///1949er.org
        ///1984bbs.com
        ///1984bbs.org
        ///1989report.hkja.org.hk
        ///199.59.148.20
        ///1991way.com
        ///1998cdp.org
        ///1bao.org
        ///1dumb.com
        ///1e100.net
        ///1eew.com
        ///1mobile.com
        ///1mobile.tw
        ///1pondo.tv
        ///2-hand.info
        ///2000fun.com
        ///2008x [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string black {
            get {
                return ResourceManager.GetString("black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 45.33.128.0/20
        ///64.233.160.0/19
        ///66.102.0.0/20
        ///66.249.80.0/20
        ///72.14.192.0/18
        ///74.125.0.0/16
        ///91.108.4.0/22
        ///91.108.8.0/21
        ///91.108.20.0/22
        ///91.108.36.0/22
        ///91.108.56.0/22
        ///101.127.206.0/23
        ///101.127.208.0/23
        ///107.178.32.0/20
        ///108.177.8.0/21
        ///109.239.140.0/24
        ///149.154.160.0/20
        ///173.194.0.0/16
        ///209.85.128.0/17
        ///216.58.192.0/19
        ///216.239.32.0/19
        /// 的本地化字符串。
        /// </summary>
        internal static string black_cidr {
            get {
                return ResourceManager.GetString("black_cidr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///    &lt;title&gt;Page Title&lt;/title&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///    &lt;script &gt;__PACFileContent__&lt;/script&gt;
        ///    &lt;style&gt;
        ///        .main-wrapper {
        ///            margin: 8px auto;
        ///            width: 100%;
        ///            max-width: 500px;
        ///        }
        ///        
        ///        .inline-block {
        ///            display: inline-block;
        ///        }
        ///        
        ///        .title {
        ///            tex [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PacDebuggerTpl {
            get {
                return ResourceManager.GetString("PacDebuggerTpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 var proxy = &apos;__PROXY__&apos;,
        ///    mode = &apos;__MODE__&apos;,
        ///    domains = { __DOMAINS__ },
        ///    cidrs = [__CIDRS__];
        ///
        ///function ip2decimal(o) { var c = o.split(&quot;.&quot;); return 256 * (256 * (256 * +c[0] + +c[1]) + +c[2]) + +c[3] }
        ///
        ///function FindProxyForURL(o, c) {
        ///    if (/\d+\.\d+\.\d+\.\d+/.test(c)) {
        ///        if (isInNet(dnsResolve(c), &quot;10.0.0.0&quot;, &quot;255.0.0.0&quot;) ||
        ///            isInNet(dnsResolve(c), &quot;172.16.0.0&quot;, &quot;255.240.0.0&quot;) ||
        ///            isInNet(dnsResolve(c), &quot;192.168.0.0&quot;, &quot;255.255.0.0&quot;) ||
        ///            isInNet(dnsReso [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PacJsTpl {
            get {
                return ResourceManager.GetString("PacJsTpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/txthinking/blackwhite 的本地化字符串。
        /// </summary>
        internal static string TxthinkingPacProjectUrl {
            get {
                return ResourceManager.GetString("TxthinkingPacProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0-6.com
        ///0001688.com
        ///001cndc.com
        ///001en.com
        ///001jm.com
        ///001job.com
        ///001pp.com
        ///001sj.net
        ///001sxy.com
        ///001uk.com
        ///001xin.com
        ///005.tv
        ///00615.net
        ///007swz.com
        ///00817.com
        ///0086gd.com
        ///01-123.com
        ///010lf.com
        ///01dai.com
        ///01dianzi.com
        ///01hr.com
        ///01w.com
        ///01wed.com
        ///020.com
        ///020h.com
        ///020job.com
        ///020p.net
        ///0214.com
        ///022china.com
        ///022job.net
        ///022net.com
        ///022s.com
        ///022v.com
        ///0231230.com
        ///023zp.com
        ///024anfang.net
        ///024zxw.com
        ///025ct.com
        ///025syedu.com
        ///025xl.com
        ///025zp.com
        ///027.net
        ///027art.com
        ///029k.com
        ///0312mc.com
        ///0316.cc
        ///0352fang.com
        ///0356f.com
        ///0357hz.com
        ///0371gao [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string white {
            get {
                return ResourceManager.GetString("white", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.0.1.0/24
        ///1.0.2.0/23
        ///1.0.8.0/21
        ///1.0.32.0/19
        ///1.1.0.0/24
        ///1.1.2.0/23
        ///1.1.4.0/22
        ///1.1.8.0/21
        ///1.1.16.0/20
        ///1.1.32.0/19
        ///1.2.0.0/23
        ///1.2.2.0/24
        ///1.2.4.0/22
        ///1.2.8.0/21
        ///1.2.16.0/20
        ///1.2.32.0/19
        ///1.2.64.0/18
        ///1.3.0.0/16
        ///1.4.1.0/24
        ///1.4.2.0/23
        ///1.4.4.0/22
        ///1.4.8.0/21
        ///1.4.16.0/20
        ///1.4.32.0/19
        ///1.4.64.0/18
        ///1.8.0.0/16
        ///1.10.0.0/21
        ///1.10.8.0/23
        ///1.10.11.0/24
        ///1.10.12.0/22
        ///1.10.16.0/20
        ///1.10.32.0/19
        ///1.10.64.0/18
        ///1.12.0.0/14
        ///1.24.0.0/13
        ///1.45.0.0/16
        ///1.48.0.0/14
        ///1.56.0.0/13
        ///1.68.0.0/14
        ///1.80.0.0/12
        ///1.116.0.0/14
        ///1.180.0.0/14
        ///1.184.0.0/15
        ///1.188 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string white_cidr {
            get {
                return ResourceManager.GetString("white_cidr", resourceCulture);
            }
        }
    }
}
