//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace V2RayGCon.Resources.Resx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class I18N {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18N() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V2RayGCon.Resources.Resx.I18N", typeof(I18N).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save current config as new server? 的本地化字符串。
        /// </summary>
        internal static string AddNewServer {
            get {
                return ResourceManager.GetString("AddNewServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add server 的本地化字符串。
        /// </summary>
        internal static string AddServer {
            get {
                return ResourceManager.GetString("AddServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add server fail, please check your settings. 的本地化字符串。
        /// </summary>
        internal static string AddServFail {
            get {
                return ResourceManager.GetString("AddServFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add server success! 的本地化字符串。
        /// </summary>
        internal static string AddServSuccess {
            get {
                return ResourceManager.GetString("AddServSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analysing import, please wait ... 的本地化字符串。
        /// </summary>
        internal static string AnalysingImport {
            get {
                return ResourceManager.GetString("AnalysingImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 And then save this text file as {0}. 的本地化字符串。
        /// </summary>
        internal static string AndThenSaveThisFileAs {
            get {
                return ResourceManager.GetString("AndThenSaveThisFileAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attach to v2ray-core process fail! 的本地化字符串。
        /// </summary>
        internal static string AttachToV2rayCoreProcessFail {
            get {
                return ResourceManager.GetString("AttachToV2rayCoreProcessFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto tracker 的本地化字符串。
        /// </summary>
        internal static string AutoTracker {
            get {
                return ResourceManager.GetString("AutoTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available examples ... 的本地化字符串。
        /// </summary>
        internal static string AvailableExamples {
            get {
                return ResourceManager.GetString("AvailableExamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Average speedtest delay:  的本地化字符串。
        /// </summary>
        internal static string AvgSpeedtestResult {
            get {
                return ResourceManager.GetString("AvgSpeedtestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel current download? 的本地化字符串。
        /// </summary>
        internal static string CancelDownload {
            get {
                return ResourceManager.GetString("CancelDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not parse json! Discard changes? 的本地化字符串。
        /// </summary>
        internal static string CannotParseJson {
            get {
                return ResourceManager.GetString("CannotParseJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 can not start. Please check logs. 的本地化字符串。
        /// </summary>
        internal static string CanNotStartPlsCheckLogs {
            get {
                return ResourceManager.GetString("CanNotStartPlsCheckLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can find original server. Delete fail! 的本地化字符串。
        /// </summary>
        internal static string CantFindOrgServDelFail {
            get {
                return ResourceManager.GetString("CantFindOrgServDelFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: can not lauch v2ray-core. 的本地化字符串。
        /// </summary>
        internal static string CantLauchCore {
            get {
                return ResourceManager.GetString("CantLauchCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CF and Google 的本地化字符串。
        /// </summary>
        internal static string CFnGoogle {
            get {
                return ResourceManager.GetString("CFnGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changes: 的本地化字符串。
        /// </summary>
        internal static string ChangesColon {
            get {
                return ResourceManager.GetString("ChangesColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for update 的本地化字符串。
        /// </summary>
        internal static string CheckForUpdate {
            get {
                return ResourceManager.GetString("CheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Concurrent V2Ray-core number:  的本地化字符串。
        /// </summary>
        internal static string ConcurrentV2RayCoreNum {
            get {
                return ResourceManager.GetString("ConcurrentV2RayCoreNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config Editor 的本地化字符串。
        /// </summary>
        internal static string ConfigEditor {
            get {
                return ResourceManager.GetString("ConfigEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConfigTester 的本地化字符串。
        /// </summary>
        internal static string ConfigTester {
            get {
                return ResourceManager.GetString("ConfigTester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to clear logs? 的本地化字符串。
        /// </summary>
        internal static string ConfirmClearLog {
            get {
                return ResourceManager.GetString("ConfirmClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear speed test results? 的本地化字符串。
        /// </summary>
        internal static string ConfirmClearSpeedTestResults {
            get {
                return ResourceManager.GetString("ConfirmClearSpeedTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear system proxy setting? 的本地化字符串。
        /// </summary>
        internal static string ConfirmClearSysProxy {
            get {
                return ResourceManager.GetString("ConfirmClearSysProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close window? 的本地化字符串。
        /// </summary>
        internal static string ConfirmCloseWindow {
            get {
                return ResourceManager.GetString("ConfirmCloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discard unsaved changes and close this window? 的本地化字符串。
        /// </summary>
        internal static string ConfirmCloseWinWithoutSave {
            get {
                return ResourceManager.GetString("ConfirmCloseWinWithoutSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DELETE ALL SERVERS? 的本地化字符串。
        /// </summary>
        internal static string ConfirmDeleteAllServers {
            get {
                return ResourceManager.GetString("ConfirmDeleteAllServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete this item? 的本地化字符串。
        /// </summary>
        internal static string ConfirmDeleteControl {
            get {
                return ResourceManager.GetString("ConfirmDeleteControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete selected servers? 的本地化字符串。
        /// </summary>
        internal static string ConfirmDeleteSelectedServers {
            get {
                return ResourceManager.GetString("ConfirmDeleteSelectedServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit program? 的本地化字符串。
        /// </summary>
        internal static string ConfirmExitApp {
            get {
                return ResourceManager.GetString("ConfirmExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import server/client configs from backup file? 的本地化字符串。
        /// </summary>
        internal static string ConfirmImportServers {
            get {
                return ResourceManager.GetString("ConfirmImportServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load user settings fail! Use default settings?
        ///Yes, use default settings.
        ///No, abort. 的本地化字符串。
        /// </summary>
        internal static string ConfirmLoadDefaultUserSettings {
            get {
                return ResourceManager.GetString("ConfirmLoadDefaultUserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current config will be cleared!
        ///Load new config? 的本地化字符串。
        /// </summary>
        internal static string ConfirmLoadNewServer {
            get {
                return ResourceManager.GetString("ConfirmLoadNewServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The original settings will be reset. Do you really want to continue? 的本地化字符串。
        /// </summary>
        internal static string ConfirmOriginalSettingWillBeReset {
            get {
                return ResourceManager.GetString("ConfirmOriginalSettingWillBeReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove v2ray-core from this computer? 的本地化字符串。
        /// </summary>
        internal static string ConfirmRemoveV2RayCore {
            get {
                return ResourceManager.GetString("ConfirmRemoveV2RayCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart all autorun servers? 的本地化字符串。
        /// </summary>
        internal static string ConfirmRestartAllAutorunServer {
            get {
                return ResourceManager.GetString("ConfirmRestartAllAutorunServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart all selected servers? 的本地化字符串。
        /// </summary>
        internal static string ConfirmRestartAllSelectedServers {
            get {
                return ResourceManager.GetString("ConfirmRestartAllSelectedServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart all running servers? 的本地化字符串。
        /// </summary>
        internal static string ConfirmRestartAllServer {
            get {
                return ResourceManager.GetString("ConfirmRestartAllServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore global import settings? 的本地化字符串。
        /// </summary>
        internal static string ConfirmRestoreGlobalImportSettings {
            get {
                return ResourceManager.GetString("ConfirmRestoreGlobalImportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore plugins setting and restart all plugins? 的本地化字符串。
        /// </summary>
        internal static string ConfirmRestorePluginsSetting {
            get {
                return ResourceManager.GetString("ConfirmRestorePluginsSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore subscription settings? 的本地化字符串。
        /// </summary>
        internal static string ConfirmRestoreSubscriptionSettings {
            get {
                return ResourceManager.GetString("ConfirmRestoreSubscriptionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save current config? 的本地化字符串。
        /// </summary>
        internal static string ConfirmSaveCurConfig {
            get {
                return ResourceManager.GetString("ConfirmSaveCurConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop all selected servers? 的本地化字符串。
        /// </summary>
        internal static string ConfirmStopAllSelectedServers {
            get {
                return ResourceManager.GetString("ConfirmStopAllSelectedServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop all servers? 的本地化字符串。
        /// </summary>
        internal static string ConfirmStopAllServer {
            get {
                return ResourceManager.GetString("ConfirmStopAllServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Newer V2RayGCon v{0} is available, upgrade now? 的本地化字符串。
        /// </summary>
        internal static string ConfirmUpgradeVgc {
            get {
                return ResourceManager.GetString("ConfirmUpgradeVgc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy fail! 的本地化字符串。
        /// </summary>
        internal static string CopyFail {
            get {
                return ResourceManager.GetString("CopyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copied to clipboard. 的本地化字符串。
        /// </summary>
        internal static string CopySuccess {
            get {
                return ResourceManager.GetString("CopySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not set local proxy address! 的本地化字符串。
        /// </summary>
        internal static string CoreCantSetLocalAddr {
            get {
                return ResourceManager.GetString("CoreCantSetLocalAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V2ray-core has stopped! 的本地化字符串。
        /// </summary>
        internal static string CoreExit {
            get {
                return ResourceManager.GetString("CoreExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create folder fail! 的本地化字符串。
        /// </summary>
        internal static string CreateFolderFail {
            get {
                return ResourceManager.GetString("CreateFolderFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current v2ray-core version is v{0} 的本地化字符串。
        /// </summary>
        internal static string CurrentCoreVerIs {
            get {
                return ResourceManager.GetString("CurrentCoreVerIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current speedtest delay:  的本地化字符串。
        /// </summary>
        internal static string CurSpeedtestResult {
            get {
                return ResourceManager.GetString("CurSpeedtestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurSysProxy:  的本地化字符串。
        /// </summary>
        internal static string CurSysProxy {
            get {
                return ResourceManager.GetString("CurSysProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data too big. Please trim down the config file. 的本地化字符串。
        /// </summary>
        internal static string DataTooBig {
            get {
                return ResourceManager.GetString("DataTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decode fail. 的本地化字符串。
        /// </summary>
        internal static string DecodeFail {
            get {
                return ResourceManager.GetString("DecodeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decode import fail! 的本地化字符串。
        /// </summary>
        internal static string DecodeImportFail {
            get {
                return ResourceManager.GetString("DecodeImportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to decode v-link! 的本地化字符串。
        /// </summary>
        internal static string DecodeVLinkFail {
            get {
                return ResourceManager.GetString("DecodeVLinkFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompress fail! 的本地化字符串。
        /// </summary>
        internal static string DecompressFileFail {
            get {
                return ResourceManager.GetString("DecompressFileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graphics configuration editor for v2ray-core. 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download cancelled! 的本地化字符串。
        /// </summary>
        internal static string DownloadCancelled {
            get {
                return ResourceManager.GetString("DownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download v2ray-core completed! 的本地化字符串。
        /// </summary>
        internal static string DownloadCompleted {
            get {
                return ResourceManager.GetString("DownloadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download fail! 的本地化字符串。
        /// </summary>
        internal static string DownloadFail {
            get {
                return ResourceManager.GetString("DownloadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading, please wait ... 的本地化字符串。
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download progress 的本地化字符串。
        /// </summary>
        internal static string DownloadProgress {
            get {
                return ResourceManager.GetString("DownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download v2ray-core 的本地化字符串。
        /// </summary>
        internal static string DownloadV2rayCore {
            get {
                return ResourceManager.GetString("DownloadV2rayCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate server 的本地化字符串。
        /// </summary>
        internal static string DuplicateServer {
            get {
                return ResourceManager.GetString("DuplicateServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot load server config. Using default config! 的本地化字符串。
        /// </summary>
        internal static string EditorCannotLoadServerConfig {
            get {
                return ResourceManager.GetString("EditorCannotLoadServerConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not parse json! Please check you config. 的本地化字符串。
        /// </summary>
        internal static string EditorCheckConfig {
            get {
                return ResourceManager.GetString("EditorCheckConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config is invalid.
        ///Discard latest changes and continue? 的本地化字符串。
        /// </summary>
        internal static string EditorDiscardChange {
            get {
                return ResourceManager.GetString("EditorDiscardChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No example for this part. 的本地化字符串。
        /// </summary>
        internal static string EditorNoExample {
            get {
                return ResourceManager.GetString("EditorNoExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config has change, save it now? 的本地化字符串。
        /// </summary>
        internal static string EditorSaveChange {
            get {
                return ResourceManager.GetString("EditorSaveChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Empty) 的本地化字符串。
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link is empty! 的本地化字符串。
        /// </summary>
        internal static string EmptyLink {
            get {
                return ResourceManager.GetString("EmptyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please download v2ray-core first!（checkout systray icon&apos;s popup menu.） 的本地化字符串。
        /// </summary>
        internal static string ExeNotFound {
            get {
                return ResourceManager.GetString("ExeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Another V2RayGCon is running, please exit first. 的本地化字符串。
        /// </summary>
        internal static string ExitOtherVGCFirst {
            get {
                return ResourceManager.GetString("ExitOtherVGCFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feedback 的本地化字符串。
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fetch update information fail! 的本地化字符串。
        /// </summary>
        internal static string FetchUpdateInfoFail {
            get {
                return ResourceManager.GetString("FetchUpdateInfoFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File check sum fail! 的本地化字符串。
        /// </summary>
        internal static string FileCheckSumFail {
            get {
                return ResourceManager.GetString("FileCheckSumFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file is in use. Please close v2ray-core first. 的本地化字符串。
        /// </summary>
        internal static string FileInUse {
            get {
                return ResourceManager.GetString("FileInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File not found! 的本地化字符串。
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find no plugin. 的本地化字符串。
        /// </summary>
        internal static string FindNoPlugin {
            get {
                return ResourceManager.GetString("FindNoPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate QRCode 的本地化字符串。
        /// </summary>
        internal static string GenQRCode {
            get {
                return ResourceManager.GetString("GenQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to generate v-link! 的本地化字符串。
        /// </summary>
        internal static string GenVLinkFail {
            get {
                return ResourceManager.GetString("GenVLinkFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get v2ray-core version fail! 的本地化字符串。
        /// </summary>
        internal static string GetCoreVerFail {
            get {
                return ResourceManager.GetString("GetCoreVerFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to get free tcp port! 的本地化字符串。
        /// </summary>
        internal static string GetFreePortFail {
            get {
                return ResourceManager.GetString("GetFreePortFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get inbound information fail! 的本地化字符串。
        /// </summary>
        internal static string GetInboundInfoFail {
            get {
                return ResourceManager.GetString("GetInboundInfoFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get latest version fail! 的本地化字符串。
        /// </summary>
        internal static string GetLatestVerFail {
            get {
                return ResourceManager.GetString("GetLatestVerFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get v2ray-core versions list fail! 的本地化字符串。
        /// </summary>
        internal static string GetVersionListFail {
            get {
                return ResourceManager.GetString("GetVersionListFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get V2RayGCon latest version number fail! 的本地化字符串。
        /// </summary>
        internal static string GetVGCVerFail {
            get {
                return ResourceManager.GetString("GetVGCVerFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global proxy 的本地化字符串。
        /// </summary>
        internal static string GlobalProxy {
            get {
                return ResourceManager.GetString("GlobalProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 can not start. Please check configuration. 的本地化字符串。
        /// </summary>
        internal static string HasFaultyConfig {
            get {
                return ResourceManager.GetString("HasFaultyConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import links from clipboard 的本地化字符串。
        /// </summary>
        internal static string ImportLink {
            get {
                return ResourceManager.GetString("ImportLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found no link! 的本地化字符串。
        /// </summary>
        internal static string ImportLinkFail {
            get {
                return ResourceManager.GetString("ImportLinkFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Success! 的本地化字符串。
        /// </summary>
        internal static string ImportLinkSuccess {
            get {
                return ResourceManager.GetString("ImportLinkSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use inbound settings in config. 的本地化字符串。
        /// </summary>
        internal static string InbModeConfigToolTip {
            get {
                return ResourceManager.GetString("InbModeConfigToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inject packageing imports fail, ignore imports. 的本地化字符串。
        /// </summary>
        internal static string InjectPackagingImportsFail {
            get {
                return ResourceManager.GetString("InjectPackagingImportsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 was killed by user or another app. 的本地化字符串。
        /// </summary>
        internal static string KilledByUserOrOtherApp {
            get {
                return ResourceManager.GetString("KilledByUserOrOtherApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last modified  的本地化字符串。
        /// </summary>
        internal static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last test is not finished yet. Please wait till test finish. 的本地化字符串。
        /// </summary>
        internal static string LastTestNoFinishYet {
            get {
                return ResourceManager.GetString("LastTestNoFinishYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 latest 的本地化字符串。
        /// </summary>
        internal static string Latest {
            get {
                return ResourceManager.GetString("Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List is empty! 的本地化字符串。
        /// </summary>
        internal static string ListIsEmpty {
            get {
                return ResourceManager.GetString("ListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load json file fail! 的本地化字符串。
        /// </summary>
        internal static string LoadJsonFail {
            get {
                return ResourceManager.GetString("LoadJsonFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log of this server 的本地化字符串。
        /// </summary>
        internal static string LogOfThisServer {
            get {
                return ResourceManager.GetString("LogOfThisServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Looks like you found a bug.
        ///Please send this bug report to the author. 的本地化字符串。
        /// </summary>
        internal static string LooksLikeABug {
            get {
                return ResourceManager.GetString("LooksLikeABug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main Window 的本地化字符串。
        /// </summary>
        internal static string MainWin {
            get {
                return ResourceManager.GetString("MainWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mark:  的本地化字符串。
        /// </summary>
        internal static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MM-dd 的本地化字符串。
        /// </summary>
        internal static string MMdd {
            get {
                return ResourceManager.GetString("MMdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiboxing 的本地化字符串。
        /// </summary>
        internal static string Multiboxing {
            get {
                return ResourceManager.GetString("Multiboxing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name:  的本地化字符串。
        /// </summary>
        internal static string NameColon {
            get {
                return ResourceManager.GetString("NameColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network timeout 的本地化字符串。
        /// </summary>
        internal static string NetworkTimeout {
            get {
                return ResourceManager.GetString("NetworkTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No links found. 的本地化字符串。
        /// </summary>
        internal static string NoLinkFound {
            get {
                return ResourceManager.GetString("NoLinkFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No mark 的本地化字符串。
        /// </summary>
        internal static string NoMark {
            get {
                return ResourceManager.GetString("NoMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current V2RayGCon is the latest version. 的本地化字符串。
        /// </summary>
        internal static string NoNewVGC {
            get {
                return ResourceManager.GetString("NoNewVGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find any QR code. 的本地化字符串。
        /// </summary>
        internal static string NoQRCode {
            get {
                return ResourceManager.GetString("NoQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No qualify proxy server available!
        ///Switch to direct download. 的本地化字符串。
        /// </summary>
        internal static string NoQualifyProxyServer {
            get {
                return ResourceManager.GetString("NoQualifyProxyServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No server available! 的本地化字符串。
        /// </summary>
        internal static string NoServerAvailable {
            get {
                return ResourceManager.GetString("NoServerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No subscription links available. 的本地化字符串。
        /// </summary>
        internal static string NoSubsUrlAvailable {
            get {
                return ResourceManager.GetString("NoSubsUrlAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 not set 的本地化字符串。
        /// </summary>
        internal static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate link or unable to decode 的本地化字符串。
        /// </summary>
        internal static string NotSupportLinkType {
            get {
                return ResourceManager.GetString("NotSupportLinkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are using the latest version now. 的本地化字符串。
        /// </summary>
        internal static string NoUpdateTryLater {
            get {
                return ResourceManager.GetString("NoUpdateTryLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 or disable portable mode. 的本地化字符串。
        /// </summary>
        internal static string OrDisablePortableMode {
            get {
                return ResourceManager.GetString("OrDisablePortableMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find original config!
        ///Please use [Add new server] or [Replace server]. 的本地化字符串。
        /// </summary>
        internal static string OrgServNotFound {
            get {
                return ResourceManager.GetString("OrgServNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package done. 的本地化字符串。
        /// </summary>
        internal static string PackageDone {
            get {
                return ResourceManager.GetString("PackageDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package failed 的本地化字符串。
        /// </summary>
        internal static string PackageFail {
            get {
                return ResourceManager.GetString("PackageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package success 的本地化字符串。
        /// </summary>
        internal static string PackageSuccess {
            get {
                return ResourceManager.GetString("PackageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PAC proxy 的本地化字符串。
        /// </summary>
        internal static string PacProxy {
            get {
                return ResourceManager.GetString("PacProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not parse json! Please check current config. 的本地化字符串。
        /// </summary>
        internal static string PleaseCheckConfig {
            get {
                return ResourceManager.GetString("PleaseCheckConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugins 的本地化字符串。
        /// </summary>
        internal static string Plugins {
            get {
                return ResourceManager.GetString("Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Portable mode 的本地化字符串。
        /// </summary>
        internal static string Portable {
            get {
                return ResourceManager.GetString("Portable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GitHub 的本地化字符串。
        /// </summary>
        internal static string ProjectPage {
            get {
                return ResourceManager.GetString("ProjectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wiki 的本地化字符串。
        /// </summary>
        internal static string ProjectWiki {
            get {
                return ResourceManager.GetString("ProjectWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy all website 的本地化字符串。
        /// </summary>
        internal static string ProxyModeAll {
            get {
                return ResourceManager.GetString("ProxyModeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No proxy 的本地化字符串。
        /// </summary>
        internal static string ProxyModeNone {
            get {
                return ResourceManager.GetString("ProxyModeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy accroding to PAC setting 的本地化字符串。
        /// </summary>
        internal static string ProxyModePAC {
            get {
                return ResourceManager.GetString("ProxyModePAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quick switch 的本地化字符串。
        /// </summary>
        internal static string QuickSwitch {
            get {
                return ResourceManager.GetString("QuickSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reason 的本地化字符串。
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remark:  的本地化字符串。
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use current config to replace selected server? 的本地化字符串。
        /// </summary>
        internal static string ReplaceServer {
            get {
                return ResourceManager.GetString("ReplaceServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as 的本地化字符串。
        /// </summary>
        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please save the modified option first! 的本地化字符串。
        /// </summary>
        internal static string SaveChangeFirst {
            get {
                return ResourceManager.GetString("SaveChangeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save settings to file fail!
        ///Please move this app to a writeable folder. 的本地化字符串。
        /// </summary>
        internal static string SaveUserSettingsToFileFail {
            get {
                return ResourceManager.GetString("SaveUserSettingsToFileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan QR code 的本地化字符串。
        /// </summary>
        internal static string ScanQRCode {
            get {
                return ResourceManager.GetString("ScanQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select ther servers first. 的本地化字符串。
        /// </summary>
        internal static string SelectServerFirst {
            get {
                return ResourceManager.GetString("SelectServerFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Servers 的本地化字符串。
        /// </summary>
        internal static string Servers {
            get {
                return ResourceManager.GetString("Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 servers are running. 的本地化字符串。
        /// </summary>
        internal static string ServersAreRunning {
            get {
                return ResourceManager.GetString("ServersAreRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please set any server as PAC proxy first. 的本地化字符串。
        /// </summary>
        internal static string SetAnyServerAsPacServerFirst {
            get {
                return ResourceManager.GetString("SetAnyServerAsPacServerFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set proxy mode 的本地化字符串。
        /// </summary>
        internal static string SetProxyMode {
            get {
                return ResourceManager.GetString("SetProxyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set system proxy complete. 的本地化字符串。
        /// </summary>
        internal static string SetSysProxyDone {
            get {
                return ResourceManager.GetString("SetSysProxyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set system proxy fail! 
        ///Please take a look at log. 的本地化字符串。
        /// </summary>
        internal static string SetSysProxyFail {
            get {
                return ResourceManager.GetString("SetSysProxyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speed test 的本地化字符串。
        /// </summary>
        internal static string SpeedTest {
            get {
                return ResourceManager.GetString("SpeedTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speed tests have finished. 的本地化字符串。
        /// </summary>
        internal static string SpeedTestFinished {
            get {
                return ResourceManager.GetString("SpeedTestFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speedtest on port:  的本地化字符串。
        /// </summary>
        internal static string SpeedtestPortNum {
            get {
                return ResourceManager.GetString("SpeedtestPortNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total {0}/{1} Selected {2}/{3} 的本地化字符串。
        /// </summary>
        internal static string StatusBarMessageTpl {
            get {
                return ResourceManager.GetString("StatusBarMessageTpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page {0}/{1} 的本地化字符串。
        /// </summary>
        internal static string StatusBarPagerInfoTpl {
            get {
                return ResourceManager.GetString("StatusBarPagerInfoTpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page {0,3} ({1,4} - {2,4}) 的本地化字符串。
        /// </summary>
        internal static string StatusBarPagerMenuItemTpl {
            get {
                return ResourceManager.GetString("StatusBarPagerMenuItemTpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop all servers 的本地化字符串。
        /// </summary>
        internal static string StopAllServers {
            get {
                return ResourceManager.GetString("StopAllServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stopping speed test. 的本地化字符串。
        /// </summary>
        internal static string StoppingSpeedtest {
            get {
                return ResourceManager.GetString("StoppingSpeedtest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop server first, please! 的本地化字符串。
        /// </summary>
        internal static string StopServerFirst {
            get {
                return ResourceManager.GetString("StopServerFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success. 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Summary:  的本地化字符串。
        /// </summary>
        internal static string SummaryColon {
            get {
                return ResourceManager.GetString("SummaryColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to a random server 的本地化字符串。
        /// </summary>
        internal static string SwitchToRandomServer {
            get {
                return ResourceManager.GetString("SwitchToRandomServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to a random TLS server 的本地化字符串。
        /// </summary>
        internal static string SwitchToRandomTlsserver {
            get {
                return ResourceManager.GetString("SwitchToRandomTlsserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your system does not support TLS1.2.
        ///Please upgrade to .NET 4.5 or higher.
        ///Otherwise operations involving the network may fail. 的本地化字符串。
        /// </summary>
        internal static string SysNotSupportTLS12 {
            get {
                return ResourceManager.GetString("SysNotSupportTLS12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set mode to HTTP or SOCKS first, please! 的本地化字符串。
        /// </summary>
        internal static string SysProxyRequireHttpOrSocksMode {
            get {
                return ResourceManager.GetString("SysProxyRequireHttpOrSocksMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System proxy must be a HTTP server. 的本地化字符串。
        /// </summary>
        internal static string SysProxyRequireHTTPServer {
            get {
                return ResourceManager.GetString("SysProxyRequireHTTPServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Testing  的本地化字符串。
        /// </summary>
        internal static string Testing {
            get {
                return ResourceManager.GetString("Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The test will take a very long time.
        ///Are you sure you want to continue? 的本地化字符串。
        /// </summary>
        internal static string TestWillTakeALongTime {
            get {
                return ResourceManager.GetString("TestWillTakeALongTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server #{0} 的本地化字符串。
        /// </summary>
        internal static string TheNthServer {
            get {
                return ResourceManager.GetString("TheNthServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout 的本地化字符串。
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total 的本地化字符串。
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total:  的本地化字符串。
        /// </summary>
        internal static string TotalNum {
            get {
                return ResourceManager.GetString("TotalNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download fail!
        ///You can download manually from the link below.
        ///https://github.com/v2ray/v2ray-core 的本地化字符串。
        /// </summary>
        internal static string TryManualDownload {
            get {
                return ResourceManager.GetString("TryManualDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unset partable mode fail!
        ///Please delete {0} in app folder. 的本地化字符串。
        /// </summary>
        internal static string UnsetPortableModeFail {
            get {
                return ResourceManager.GetString("UnsetPortableModeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking for update, please wait.
        ///If last update fail, please restart this software and try again. 的本地化字符串。
        /// </summary>
        internal static string UpdatingPleaseWait {
            get {
                return ResourceManager.GetString("UpdatingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use decode cache. 的本地化字符串。
        /// </summary>
        internal static string UsingDecodeCache {
            get {
                return ResourceManager.GetString("UsingDecodeCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} exited with error code {1}!
        ///Please check server configuration and log. 的本地化字符串。
        /// </summary>
        internal static string V2rayCoreExitAbnormally {
            get {
                return ResourceManager.GetString("V2rayCoreExitAbnormally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vist v2ray-core release webpage? 的本地化字符串。
        /// </summary>
        internal static string VisitV2rayCoreReleasePage {
            get {
                return ResourceManager.GetString("VisitV2rayCoreReleasePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vist V2RayGCon issue webpage? 的本地化字符串。
        /// </summary>
        internal static string VisitVGCIssuePage {
            get {
                return ResourceManager.GetString("VisitVGCIssuePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visit the following webpage? 的本地化字符串。
        /// </summary>
        internal static string VisitWebPage {
            get {
                return ResourceManager.GetString("VisitWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vist project webpage? 的本地化字符串。
        /// </summary>
        internal static string VistProjectPage {
            get {
                return ResourceManager.GetString("VistProjectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visit user manual webpage? 的本地化字符串。
        /// </summary>
        internal static string VistWikiPage {
            get {
                return ResourceManager.GetString("VistWikiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notice! IE not support PAC. 的本地化字符串。
        /// </summary>
        internal static string WarnIENotSupportPac {
            get {
                return ResourceManager.GetString("WarnIENotSupportPac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: 的本地化字符串。
        /// </summary>
        internal static string WarningColon {
            get {
                return ResourceManager.GetString("WarningColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Another instance is already running.
        ///Are you sure to launch another one? 的本地化字符串。
        /// </summary>
        internal static string WarnMultipleInstance {
            get {
                return ResourceManager.GetString("WarnMultipleInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 32bit 的本地化字符串。
        /// </summary>
        internal static string Win32 {
            get {
                return ResourceManager.GetString("Win32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 64bit 的本地化字符串。
        /// </summary>
        internal static string Win64 {
            get {
                return ResourceManager.GetString("Win64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 的本地化字符串。
        /// </summary>
        internal static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write to file fail! 的本地化字符串。
        /// </summary>
        internal static string WriteFileFail {
            get {
                return ResourceManager.GetString("WriteFileFail", resourceCulture);
            }
        }
    }
}
