//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace V2RayGCon.Resources.Resx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StrConst {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StrConst() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V2RayGCon.Resources.Resx.StrConst", typeof(StrConst).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;fakednsDefault&quot;: [
        ///    {
        ///      &quot;ipPool&quot;: &quot;198.18.0.0/15&quot;,
        ///      &quot;poolSize&quot;: 65535
        ///    },
        ///    {
        ///      &quot;ipPool&quot;: &quot;fc00::/18&quot;,
        ///      &quot;poolSize&quot;: 65535
        ///    }
        ///  ],
        ///  &quot;observatoryDefault&quot;: {
        ///    &quot;subjectSelector&quot;: [
        ///      &quot;outbound&quot;
        ///    ]
        ///  },
        ///  &quot;observatoryUrlAndInterval&quot;: {
        ///    &quot;subjectSelector&quot;: [
        ///      &quot;agentout&quot;
        ///    ],
        ///    &quot;probeURL&quot;: &quot;https://api.v2fly.org/checkConnection.svgz&quot;,
        ///    &quot;probeInterval&quot;: &quot;5000ms&quot;
        ///  },
        ///  &quot;browserForwarderDefault&quot;: {
        ///    &quot;listenAddr&quot;: &quot;127.0.0.1&quot;,
        ///    [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string config_example {
            get {
                return ResourceManager.GetString("config_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;log&quot;: {
        ///    &quot;loglevel&quot;: &quot;warning&quot;
        ///  },
        ///  &quot;inbounds&quot;: [
        ///    {
        ///      &quot;port&quot;: 1080,
        ///      &quot;listen&quot;: &quot;127.0.0.1&quot;,
        ///      &quot;protocol&quot;: &quot;socks&quot;,
        ///      &quot;settings&quot;: {
        ///        &quot;auth&quot;: &quot;noauth&quot;,
        ///        &quot;udp&quot;: false,
        ///        &quot;ip&quot;: &quot;127.0.0.1&quot;
        ///      }
        ///    }
        ///  ],
        ///  &quot;outbounds&quot;: [
        ///    {
        ///      &quot;protocol&quot;: &quot;freedom&quot;,
        ///      &quot;settings&quot;: {},
        ///      &quot;tag&quot;: &quot;direct&quot;
        ///    }
        ///  ],
        ///  &quot;policy&quot;: {
        ///    &quot;levels&quot;: {
        ///      &quot;0&quot;: {
        ///        &quot;uplinkOnly&quot;: 0
        ///      }
        ///    }
        ///  }
        ///} 的本地化字符串。
        /// </summary>
        internal static string config_min {
            get {
                return ResourceManager.GetString("config_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;chainV4Tpl&quot;: {
        ///    &quot;log&quot;: {
        ///      &quot;loglevel&quot;: &quot;warning&quot;
        ///    },
        ///    &quot;v2raygcon&quot;: {
        ///      &quot;alias&quot;: &quot;PackageV4&quot;,
        ///      &quot;description&quot;: &quot;&quot;
        ///    },
        ///    &quot;inbounds&quot;: [
        ///      {
        ///        &quot;port&quot;: 1080,
        ///        &quot;listen&quot;: &quot;127.0.0.1&quot;,
        ///        &quot;protocol&quot;: &quot;socks&quot;,
        ///        &quot;settings&quot;: {},
        ///        &quot;tag&quot;: &quot;agentin&quot;
        ///      }
        ///    ],
        ///    &quot;outbounds&quot;: []
        ///  },
        ///  &quot;pkgV4Tpl&quot;: {
        ///    &quot;log&quot;: {
        ///      &quot;loglevel&quot;: &quot;warning&quot;
        ///    },
        ///    &quot;v2raygcon&quot;: {
        ///      &quot;alias&quot;: &quot;PackageV4&quot;,
        ///      &quot;description&quot;: &quot;&quot;
        ///    },        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string config_pkg {
            get {
                return ResourceManager.GetString("config_pkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;statsApiV4Inb&quot;: {
        ///    &quot;inbounds&quot;: [
        ///      {
        ///        &quot;listen&quot;: &quot;127.0.0.1&quot;,
        ///        &quot;port&quot;: 1090,
        ///        &quot;protocol&quot;: &quot;dokodemo-door&quot;,
        ///        &quot;settings&quot;: {
        ///          &quot;address&quot;: &quot;127.0.0.1&quot;
        ///        },
        ///        &quot;tag&quot;: &quot;StatsApiInb&quot;
        ///      }
        ///    ]
        ///  },
        ///  &quot;statsApiV4Tpl&quot;: {
        ///    &quot;policy&quot;: {
        ///      &quot;levels&quot;: {
        ///        &quot;0&quot;: {
        ///          &quot;statsUserUplink&quot;: true,
        ///          &quot;statsUserDownlink&quot;: true
        ///        }
        ///      },
        ///      &quot;system&quot;: {
        ///        &quot;statsInboundUplink&quot;: true,
        ///        &quot;statsInbound [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string config_tpl {
            get {
                return ResourceManager.GetString("config_tpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0.0.0.0
        ///0.0.0.0/8
        ///1.1
        ///1.1.1.1
        ///10.0.0.0/8
        ///1080
        ///127.0.0.1
        ///192.168.1.1
        ///200
        ///53
        ///8.8.8.8
        ///8080
        ///Accept-Encoding
        ///acceptProxyProtocol
        ///agentout
        ///AsIs
        ///browserForwarder
        ///Connection
        ///GET
        ///grpc
        ///grpcSettings
        ///Host
        ///IPIfNonMatch
        ///IPOnDemand
        ///Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
        ///Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46
        ///multiMode
        ///OK [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ConfigJsonKeywords {
            get {
                return ResourceManager.GetString("ConfigJsonKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DO NOT REMOVE THIS FILE! 的本地化字符串。
        /// </summary>
        internal static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 stat: \&lt;.+?name: &quot;([^&quot;]+)&quot;([^&gt;]+?value: (\d+))?.+?&gt; 的本地化字符串。
        /// </summary>
        internal static string StatApiResultPattern {
            get {
                return ResourceManager.GetString("StatApiResultPattern", resourceCulture);
            }
        }
    }
}
